# Licensed under a 3-clause BSD style license - see LICENSE.rst

zalert_names = ['alerts', 'nights', 'alerts_obsid', 'alerts_pid',
                'alerts_ssnamenr']

schema = '''
CREATE TABLE IF NOT EXISTS nights(
  nightid INTEGER PRIMARY KEY,
  date TEXT UNIQUE,
  alerts INTEGER,
  retrieved TEXT
);

CREATE TABLE IF NOT EXISTS alerts(
  nightid INTEGER,
  obsid INTEGER,
  jd FLOAT,
  fid INT,
  pid INT,
  diffmaglim FLOAT,
  pdiffimfilename TEXT,
  programpi TEXT,
  programid INT,
  candid INTEGER PRIMARY KEY,
  isdiffpos TEXT,
  tblid INT,
  nid INT,
  rcid INT,
  field INT,
  xpos FLOAT,
  ypos FLOAT,
  ra FLOAT,
  dec FLOAT,
  magpsf FLOAT,
  sigmapsf FLOAT,
  chipsf FLOAT,
  magap FLOAT,
  sigmagap FLOAT,
  distnr FLOAT,
  magnr FLOAT,
  sigmagnr FLOAT,
  chinr FLOAT,
  sharpnr FLOAT,
  sky FLOAT,
  magdiff FLOAT,
  fwhm FLOAT,
  classtar FLOAT,
  mindtoedge FLOAT,
  magfromlim FLOAT,
  seeratio FLOAT,
  aimage FLOAT,
  bimage FLOAT,
  aimagerat FLOAT,
  bimagerat FLOAT,
  elong FLOAT,
  nneg INT,
  nbad INT,
  rb FLOAT,
  ssdistnr FLOAT,
  ssmagnr FLOAT,
  ssnamenr TEXT,
  sumrat FLOAT,
  magapbig FLOAT,
  sigmagapbig FLOAT,
  ranr FLOAT,
  decnr FLOAT,
  sgmag1 FLOAT,
  srmag1 FLOAT,
  simag1 FLOAT,
  szmag1 FLOAT,
  sgscore1 FLOAT,
  distpsnr1 FLOAT,
  ndethist INT,
  ncovhist INT,
  jdstarthist FLOAT,
  jdendhist FLOAT,
  scorr FLOAT,
  tooflag INT,
  objectidps1 INT,
  objectidps2 INT,
  sgmag2 FLOAT,
  srmag2 FLOAT,
  simag2 FLOAT,
  szmag2 FLOAT,
  sgscore2 FLOAT,
  distpsnr2 FLOAT,
  objectidps3 INT,
  sgmag3 FLOAT,
  srmag3 FLOAT,
  simag3 FLOAT,
  szmag3 FLOAT,
  sgscore3 FLOAT,
  distpsnr3 FLOAT,
  nmtchps INT,
  rfid INT,
  jdstartref FLOAT,
  jdendref FLOAT,
  nframesref INT,
  exptime FLOAT,
  FOREIGN KEY(nightid) REFERENCES nights(nightid)
  FOREIGN KEY(obsid) REFERENCES obs(obsid)
);

CREATE INDEX IF NOT EXISTS alerts_obsid ON alerts (obsid);
CREATE INDEX IF NOT EXISTS alerts_pid ON alerts (pid);
CREATE INDEX IF NOT EXISTS alerts_ssnamenr ON alerts (ssnamenr);
'''
